In [1]:
import csv
import pandas as pd
import numpy as npy

In [2]:
# Link to data: https://www.kaggle.com/sobhanmoosavi/us-accidents
# The file was too big to upload to github so you can download it above
# and save it locally to get this code to run.
accident_file = "US_Accidents_Dec20.csv"

In [3]:
full_data = pd.read_csv(accident_file)
full_data.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [9]:
#full_data

In [10]:
# Separate data into years for smaller import

full_data_2019 = full_data[full_data["Year"]=="2019"]
#full_data_2019
full_data_2020 = full_data[full_data["Year"]=="2020"]
#full_data_2020
#full_data_2016 = full_data[full_data["Year"]=="2016"]
#full_data_2016
#full_data_2017 = full_data[full_data["Year"]=="2017"]
#full_data_2017
#full_data_2018 = full_data[full_data["Year"]=="2018"]
#full_data_2018

In [11]:
#879178 = false
#len(full_data_2019)

In [12]:
# Drop duplicates from all years

full_data_2019.drop_duplicates().reset_index()
full_data_2020.drop_duplicates().reset_index()
#full_data_2016.drop_duplicates().reset_index()
#full_data_2017.drop_duplicates().reset_index()
#full_data_2018.drop_duplicates().reset_index()

,index,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Year
0,512217,A-512230,MapQuest,201.0,2,2020-12-31 10:47:49,2020-12-31 12:19:16,43.207451,-78.650032,NaN,...,False,False,False,False,False,Day,Day,Day,Day,2020
1,512218,A-512231,MapQuest,201.0,2,2020-12-31 13:24:43,2020-12-31 13:54:32,43.030651,-78.875862,NaN,...,False,False,False,True,False,Day,Day,Day,Day,2020
2,512219,A-512232,MapQuest,201.0,3,2020-12-31 13:29:34,2020-12-31 14:59:19,42.550568,-79.108765,NaN,...,False,False,False,False,False,Day,Day,Day,Day,2020
3,512220,A-512233,MapQuest,201.0,2,2020-12-31 04:35:33,2020-12-31 05:35:36,42.362038,-71.071365,NaN,...,False,False,False,False,False,Night,Night,Night,Night,2020
4,512221,A-512234,MapQuest,201.0,2,2020-12-31 05:11:11,2020-12-31 07:00:16,42.357281,-71.128036,NaN,...,True,False,False,True,False,Night,Night,Night,Night,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258151,3741840,A-3748701,Bing,NaN,2,2020-01-06 20:59:00,2020-01-06 21:32:38,34.265778,-118.454289,34.265778,...,False,False,False,False,False,Night,Night,Night,Night,2020
1258152,3741841,A-3748702,Bing,NaN,2,2020-01-06 21:14:00,2020-01-06 23:16:38,35.736667,-119.742500,35.736667,...,False,False,False,False,False,Night,Night,Night,Night,2020
1258153,3741842,A-3748703,Bing,NaN,2,2020-01-06 21:19:00,2020-01-06 22:19:37,34.075263,-118.281157,34.075263,...,False,False,False,False,False,Night,Night,Night,Night,2020
1258154,3752192,A-3759053,Bing,NaN,2,2020-01-01 00:08:02,2020-01-01 00:37:03,42.315690,-83.085920,42.312500,...,False,False,False,False,False,Night,Night,Night,Night,2020
1258155,3752228,A-3759089,Bing,NaN,4,2020-01-01 00:31:17,2020-01-01 00:59:51,38.840700,-76.942320,38.840730,...,False,False,False,True,False,Night,Night,Night,Night,2020

In [13]:
full_data_2019 = full_data_2019[['Severity','Start_Lat','Start_Lng','Street','City','County','State','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']]
#full_data_2019.head()
full_data_2020 = full_data_2020[['Severity','Start_Lat','Start_Lng','Street','City','County','State','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']]
#full_data_2019.head()

In [14]:
# Check for null values using value_counts()
#columns = ['Severity','Start_Lat','Start_Lng','Street','City','County','State','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']
#for column in columns:
    #print(full_data_2019.isnull()[column].value_counts())

In [15]:
#print(full_data_2019.isnull()["Precipitation(in)"].value_counts())

In [16]:
#unique on state to see what state is missing
#state_list = ['AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'IA',
#       'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN',
#      'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY',
#     'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
#    'VT', 'WA', 'WI', 'WV', 'WY']

In [17]:
#print(state_list)

In [18]:
# Drop NA values from each year

full_data_2019 = full_data_2019.dropna()
full_data_2020 = full_data_2020.dropna()
#full_data_2016 = full_data_2016.dropna()
#full_data_2017 = full_data_2017.dropna()
#full_data_2018 = full_data_2018.dropna()
#len(full_data_2020)

In [19]:
full_data_2019.to_csv('Accident_Data_2019_dropna.csv', index=False)
full_data_2020.to_csv('Accident_Data_2020_dropna.csv', index=False)
#full_data_2016.to_csv('Accident_Data_2016_dropna.csv', index=False)
#full_data_2017.to_csv('Accident_Data_2017_dropna.csv', index=False)
#full_data_2018.to_csv('Accident_Data_2018_dropna.csv', index=False)

In [20]:
# Run test code below to check for number of data points per state.
#full_data_2019.groupby('State')['State'].size()

In [21]:
#Divisions = {['Pacific','WA','OR','CA'],
#            ['Mountain','MT','ID','NV','WY','UT','CO','AZ','NM'],
#            ['West North Central','ND','SD','NE','KS','MN','IA','MO'],
#            ['West South Central','TX','OK','AR','LA'],
#            ['East North Central','WI','IL','MI','IN','OH'],
#            ['East South Central','KY','TN','MS','AL'],
#            ['New England','ME','VT','NH','MA','CT','RI'],
#            ['Middle Atlantic','NY','NJ','PA'],
#            ['South Atlantic','WV','DE','MD','VA','NC','SC','GA','FL']}

# Create 2019 data frames based off the nine different divisions above
full_data_2019_pacific_divison = full_data_2019[(full_data_2019['State'] == 'WA') | (full_data_2019['State'] == 'OR') | (full_data_2019['State'] == 'CA')].sample(10000)
#full_data_2019_pacific_divison.head()
full_data_2019_mountain_divison = full_data_2019[(full_data_2019['State'] == 'MT') | (full_data_2019['State'] == 'ID') | (full_data_2019['State'] == 'NV') | (full_data_2019['State'] == 'WY') | (full_data_2019['State'] == 'UT') | (full_data_2019['State'] == 'CO') | (full_data_2019['State'] == 'AZ') | (full_data_2019['State'] == 'NM')].sample(10000)
#full_data_2019_mountain_divison.head()
full_data_2019_west_north_central_divison = full_data_2019[(full_data_2019['State'] == 'ND') | (full_data_2019['State'] == 'SD') | (full_data_2019['State'] == 'NE') | (full_data_2019['State'] == 'KS') | (full_data_2019['State'] == 'MN') | (full_data_2019['State'] == 'IA') | (full_data_2019['State'] == 'MO')].sample(10000)
#full_data_2019_west_north_central_divison.head()
full_data_2019_west_south_central_divison = full_data_2019[(full_data_2019['State'] == 'TX') | (full_data_2019['State'] == 'OK') | (full_data_2019['State'] == 'AR') | (full_data_2019['State'] == 'LA')].sample(10000)
#full_data_2019_west_south_central_divison.head()
full_data_2019_east_north_central_divison = full_data_2019[(full_data_2019['State'] == 'WI') | (full_data_2019['State'] == 'IL') | (full_data_2019['State'] == 'MI') | (full_data_2019['State'] == 'IN') | (full_data_2019['State'] == 'OH')].sample(10000)
#full_data_2019_east_north_central_divison.head()
full_data_2019_east_south_central_divison = full_data_2019[(full_data_2019['State'] == 'KY') | (full_data_2019['State'] == 'TN') | (full_data_2019['State'] == 'MS') | (full_data_2019['State'] == 'AL')].sample(10000)
#full_data_2019_east_south_central_divison.head()
full_data_2019_new_england_divison = full_data_2019[(full_data_2019['State'] == 'ME') | (full_data_2019['State'] == 'VT') | (full_data_2019['State'] == 'NH') | (full_data_2019['State'] == 'MA') | (full_data_2019['State'] == 'CT') | (full_data_2019['State'] == 'RI')].sample(10000)
#full_data_2019_new_england_divison.head()
full_data_2019_middle_atlantic_divison = full_data_2019[(full_data_2019['State'] == 'NY') | (full_data_2019['State'] == 'NJ') | (full_data_2019['State'] == 'PA')].sample(10000)
#full_data_2019_middle_atlantic_divison.head()
full_data_2019_south_atlantic_divison = full_data_2019[(full_data_2019['State'] == 'WV') | (full_data_2019['State'] == 'DE') | (full_data_2019['State'] == 'MD') | (full_data_2019['State'] == 'VA') | (full_data_2019['State'] == 'NC') | (full_data_2019['State'] == 'SC') | (full_data_2019['State'] == 'GA') | (full_data_2019['State'] == 'FL')].sample(10000)
#full_data_2019_south_atlantic_divison.head()

# Save 2019 data frames as csv files
full_data_2019_pacific_divison.to_csv('2019_pacific_division.csv', index=False)
full_data_2019_mountain_divison.to_csv('2019_mountain_divison.csv', index=False)
full_data_2019_west_north_central_divison.to_csv('2019_west_north_central_division.csv', index=False)
full_data_2019_west_south_central_divison.to_csv('2019_west_south_central_division.csv', index=False)
full_data_2019_east_north_central_divison.to_csv('2019_east_north_central_division.csv', index=False)
full_data_2019_east_south_central_divison.to_csv('2019_east_south_central_division.csv', index=False)
full_data_2019_new_england_divison.to_csv('2019_new_england_division.csv', index=False)
full_data_2019_middle_atlantic_divison.to_csv('2019_middle_atlantic_division.csv', index=False)
full_data_2019_south_atlantic_divison.to_csv('2019_south_atlantic_division.csv', index=False)

# Create 2020 data frames based off the nine different divisions above
full_data_2020_pacific_divison = full_data_2020[(full_data_2020['State'] == 'WA') | (full_data_2020['State'] == 'OR') | (full_data_2020['State'] == 'CA')].sample(10000)
#full_data_2020_pacific_divison.head()
full_data_2020_mountain_divison = full_data_2020[(full_data_2020['State'] == 'MT') | (full_data_2020['State'] == 'ID') | (full_data_2020['State'] == 'NV') | (full_data_2020['State'] == 'WY') | (full_data_2020['State'] == 'UT') | (full_data_2020['State'] == 'CO') | (full_data_2020['State'] == 'AZ') | (full_data_2020['State'] == 'NM')].sample(10000)
#full_data_2020_mountain_divison.head()
full_data_2020_west_north_central_divison = full_data_2020[(full_data_2020['State'] == 'ND') | (full_data_2020['State'] == 'SD') | (full_data_2020['State'] == 'NE') | (full_data_2020['State'] == 'KS') | (full_data_2020['State'] == 'MN') | (full_data_2020['State'] == 'IA') | (full_data_2020['State'] == 'MO')].sample(10000)
#full_data_2020_west_north_central_divison.head()
full_data_2020_west_south_central_divison = full_data_2020[(full_data_2020['State'] == 'TX') | (full_data_2020['State'] == 'OK') | (full_data_2020['State'] == 'AR') | (full_data_2020['State'] == 'LA')].sample(10000)
#full_data_2020_west_south_central_divison.head()
full_data_2020_east_north_central_divison = full_data_2020[(full_data_2020['State'] == 'WI') | (full_data_2020['State'] == 'IL') | (full_data_2020['State'] == 'MI') | (full_data_2020['State'] == 'IN') | (full_data_2020['State'] == 'OH')].sample(10000)
#full_data_2020_east_north_central_divison.head()
full_data_2020_east_south_central_divison = full_data_2020[(full_data_2020['State'] == 'KY') | (full_data_2020['State'] == 'TN') | (full_data_2020['State'] == 'MS') | (full_data_2020['State'] == 'AL')].sample(10000)
#full_data_2020_east_south_central_divison.head()
full_data_2020_new_england_divison = full_data_2020[(full_data_2020['State'] == 'ME') | (full_data_2020['State'] == 'VT') | (full_data_2020['State'] == 'NH') | (full_data_2020['State'] == 'MA') | (full_data_2020['State'] == 'CT') | (full_data_2020['State'] == 'RI')].sample(10000)
#full_data_2020_new_england_divison.head()
full_data_2020_middle_atlantic_divison = full_data_2020[(full_data_2020['State'] == 'NY') | (full_data_2020['State'] == 'NJ') | (full_data_2020['State'] == 'PA')].sample(10000)
#full_data_2020_middle_atlantic_divison.head()
full_data_2020_south_atlantic_divison = full_data_2020[(full_data_2020['State'] == 'WV') | (full_data_2020['State'] == 'DE') | (full_data_2020['State'] == 'MD') | (full_data_2020['State'] == 'VA') | (full_data_2020['State'] == 'NC') | (full_data_2020['State'] == 'SC') | (full_data_2020['State'] == 'GA') | (full_data_2020['State'] == 'FL')].sample(10000)
#full_data_2020_south_atlantic_divison.head()

# Save 2020 data frames as csv files
full_data_2020_pacific_divison.to_csv('2020_pacific_division.csv', index=False)
full_data_2020_mountain_divison.to_csv('2020_mountain_divison.csv', index=False)
full_data_2020_west_north_central_divison.to_csv('2020_west_north_central_division.csv', index=False)
full_data_2020_west_south_central_divison.to_csv('2020_west_south_central_division.csv', index=False)
full_data_2020_east_north_central_divison.to_csv('2020_east_north_central_division.csv', index=False)
full_data_2020_east_south_central_divison.to_csv('2020_east_south_central_division.csv', index=False)
full_data_2020_new_england_divison.to_csv('2020_new_england_division.csv', index=False)
full_data_2020_middle_atlantic_divison.to_csv('2020_middle_atlantic_division.csv', index=False)
full_data_2020_south_atlantic_divison.to_csv('2020_south_atlantic_division.csv', index=False)